"""empty message

Revision ID: ef2d78b803b0
Revises: 
Create Date: 2019-09-24 02:27:19.886307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2d78b803b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasetlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('desc_info', sa.String(length=255), nullable=True),
    sa.Column('license_desc', sa.String(length=100), nullable=True),
    sa.Column('stars', sa.String(length=11), nullable=True),
    sa.Column('contributor_user', sa.String(length=20), nullable=True),
    sa.Column('project_year', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasetlist')
    # ### end Alembic commands ###
