# Generated by Django 2.2.5 on 2019-09-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlembicVersion',
            fields=[
                ('version_num', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'alembic_version',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datasetlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_info', models.CharField(blank=True, max_length=255, null=True)),
                ('license_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.CharField(blank=True, max_length=11, null=True)),
                ('contributor_user', models.CharField(blank=True, max_length=20, null=True)),
                ('project_year', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'datasetlist',
                'managed': False,
            },
        ),
    ]
