# Generated by Django 2.2.5 on 2019-10-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(auto_created=True, default=0, unique=True)),
                ('cateinfo', models.CharField(choices=[('1', 'CV'), ('2', 'NLP'), ('3', 'Self-driving'), ('4', 'QA'), ('5', 'Audio'), ('6', 'Medical')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Datasetlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_info', models.CharField(blank=True, max_length=255, null=True)),
                ('license_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('stars', models.CharField(blank=True, max_length=11, null=True)),
                ('contributor_user', models.CharField(blank=True, max_length=20, null=True)),
                ('project_year', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.CharField(blank=True, max_length=40, null=True)),
                ('cateinfo', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='datasetlist.DatasetCategory')),
            ],
        ),
    ]
