# Generated by Django 2.2.5 on 2019-10-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlist',
            name='cateinfo',
            field=models.CharField(choices=[('1', 'CV'), ('2', 'NLP'), ('3', 'Self-driving'), ('4', 'QA'), ('5', 'Audio'), ('6', 'Medical')], default='', max_length=10),
        ),
        migrations.DeleteModel(
            name='DatasetCategory',
        ),
    ]
