# Generated by Django 2.2.5 on 2019-10-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasetlist', '0002_auto_20191011_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetlist',
            name='cateinfo',
            field=models.CharField(choices=[('cv', 'CV'), ('nlp', 'NLP'), ('selfdriving', 'Self-driving'), ('qa', 'QA'), ('audio', 'Audio'), ('medical', 'Medical')], default='', max_length=10),
        ),
    ]
